### ISSUE TITLE
Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de criar uma nova quest e exibi-la na visualização das Quests

### ISSUE THREAD

**Issue by J-c0d3r** [S204-Inatel-2022-2/This-is-Me-App#17]
## Descrição
Criar e mostrar a quest criada na lista de quests do usuário.
O usuário deverá entrar, pelo menos, com o nome da task.
Terá a possibilidade de escolher a cor da task.
Poderá entrar com uma breve descrição de sua task.
Terá a opção de escolha em adicionar a task ao desenvolvimento de alguma skill que foi definida anteriormente.
Por fim, poderá escolher quais dias da semana irá realizar a task, poderá definir o horário de início e fim e se irá repetir o mesmo horário para os dias escolhidos ou terá um horário para cada dia.

## Historia
Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de criar uma nova quest e exibi-la na visualização das Quests

## Sub-tasks
- [ ] (Area menu) Botão de Voltar para a tela anterior; Nome da tela(Nova Quest); Botão Criar 
- [ ] Campo Nome da Task
- [ ] Botão para a escolher a cor da task
- [ ] Campo Breve Descrição
- [ ] (Layout) Descrição e botão para a escolha de uma skill
- [ ] Funcionalidade: Repetir todos os dias?
- [ ] Funcionalidade(Horário de Inicio e Horário de fim da task): Periodo: Inicio Fim 
- [ ] Funcionalidade: Escolher entre os dias da semana
- [ ] Funcionalidade: Repetir mesmo horário todos os dias?
- [ ] Funcionalidade: Definir os horário(inicio e fim) referente aos dias escolhidos

## Regras de negócio:
- [ ] Para a Quest ser criada precisa necessariamente de pelo menos um nome
- [ ] A quest poderá ser criada sem a escolha de uma skill no botão "SKILLS:"
- [ ] Uma aprovação da equipe de front-end.
- [ ] Conter todos os botões do design

## Links para acesso do material:
[Link do Figma](https://www.figma.com/file/vFvH2cUu6aDYqFWjMHTIGn/This-is-Me?node-id=7%3A12)
[Link da fonte do titulo](https://fonts.google.com/?query=jura)
[Link das Imagens](https://drive.google.com/drive/folders/19crN-SzJqV69z4VhSZgJugZOhRnHmsgS?usp=sharing)

## Design Tela
![Image](https://user-images.githubusercontent.com/60818421/190813705-2f0a549f-e3f1-490a-9213-cff1e4fd2087.png)
