### ISSUE TITLE
[US] Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de entrar com uma conta já existente para acessar a aplicação

### ISSUE THREAD

**Issue by RedfoxGHS** [S204-Inatel-2022-2/This-is-Me-App#22]
## Descrição
Quando o usuário entrar nessa tela ele deverá informar seu email e senha já cadastrados no sistema. Caso alguma das informações inseridas não estiver corretas o sistema deverá apresentar uma mensagem informando que os dados são inválidos.
Caso o usuário obtenha sucesso no login, o sistema deverá redireciona-lo a tela de de Quadros.
Caso o usuário não tenha uma conta, ele poderá criar uma nova conta ao clicar no botão NOVA CONTA onde será redirecionado para a tela Cadastro.

## Historia
Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de entrar com uma conta já existente para acessar a aplicação

## Regras de negócio:
- Email precisa estar em um formato válido. Caso não esteja deverá mostrar uma mensagem "Informações nos campos inválidos".
- Precisa validar se o email e a senha estão registrado no banco. Caso não esteja deverá mostrar uma mensagem "conta não encontrada"
- Conter todos os botões do design
- Uma aprovação da equipe de front-end/back-end

### Back-end
- [x] [Crias Endpoint Login#4](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/4)
- [x] [Configurar Spring Security com JWT#17](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/17)

### Front-end
- [x] [Criar tela login#11](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/11)
- [x] [Integrar Tela Login com API#20](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/20)

## Links para acesso do material:
[Link do Figma](https://www.figma.com/file/vFvH2cUu6aDYqFWjMHTIGn/This-is-Me?node-id=7%3A12)
[Link da fonte do titulo](https://fonts.google.com/?query=jura)
[Link das Imagens](https://drive.google.com/drive/folders/19crN-SzJqV69z4VhSZgJugZOhRnHmsgS?usp=sharing)

## Design Tela
![Image](https://user-images.githubusercontent.com/60818421/192305326-a84f6bb0-82d2-420a-a624-331e7b1f1fd7.png)
