### ISSUE TITLE
[US] Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de cadastrar uma nova conta para acessar a aplicação

### ISSUE THREAD

**Issue by RedfoxGHS** [S204-Inatel-2022-2/This-is-Me-App#23]
## Descrição
Quando o usuário entrar nessa tela ele deverá criar um username para ele, escolher o sexo, informar um email válido e criar uma senha.
Após ter preenchido todos os campos, o usuário poderá avançar clicando no botão CADASTRAR.

## Historia
Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de cadastrar uma nova conta para acessar a aplicação.

## Regras de negócio:
- Para que seja possível avançar para a próxima tela o usuário deve ter preenchido os campos Username, Email, Password e Password again
- Email precisa estar em um formato válido
- A senha precisa conter mais de 6 caracteres
- Ambas as senhas precisam estar iguais
- Conter todos os botões do design
- Uma aprovação da equipe de front-end.

### Back-end
- [x] [Criar Endpoint Cadastro#10](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/10)
- [x] [Criar Endpoint Criar Personagem ao cadastrar#14](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/14)
- [x] [Ajuste Character add Field#20](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/20)
- [x] [Ajuste Character add Field clothes]()

### Front-end
- [x] [Criar tela cadastro#12](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/12)
- [x] [Criar tela de criação de Personagem#13](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/13)
- [x] [Integrar tela cadastro com API#21](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/21)

## Links para acesso do material:
[Link do Figma](https://www.figma.com/file/vFvH2cUu6aDYqFWjMHTIGn/This-is-Me?node-id=7%3A12)
[Link da fonte do titulo](https://fonts.google.com/?query=jura)
[Link das Imagens](https://drive.google.com/drive/folders/19crN-SzJqV69z4VhSZgJugZOhRnHmsgS?usp=sharing)

## Design Tela
![Image](https://user-images.githubusercontent.com/48630726/193961747-2601522e-a4f3-4f4e-8a4e-c7750b9e75ac.png)

**Comment by RedfoxGHS** [comment]
## Debito Tecnico
