### ISSUE TITLE
[US] Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de visualizar o andamento de minhas Quests

### ISSUE THREAD

**Issue by RedfoxGHS** [S204-Inatel-2022-2/This-is-Me-App#24]
## Descrição
Nesta tela o usuário poderá visualizar seu personagem ao fundo(com o username mais seu lvl, e poderá ver isso acima da cabeça do personagem), uma lista contendo as suas quests(com as informações de cada quest) e, no rodapé da tela, os botões Skill, Agenda, Amigos, Ranks e Perfil.

O usuário poderá alterar as listas de quests entre Quests Atrasadas, Quests do Dia, Quests da Semana e Próxima Semana.

Em cada lista de quests conterá as quests que estão contidas naquela lista em formato card onde terá como informações: Nome da Quest, Skill(caso aquela quest pertença a alguma skill), Quantidade de XP, Horário, Tempo da quest.

## Historia
Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de visualizar o andamento de minhas Quests

## Regras de negócio:
- Conter todos os botões do design
- Uma aprovação da equipe de front-end.

### Back-end
- [x] [Implementar rota para buscar Quest do dia#26](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/26)
- [x] [Implementar rota para buscar Quest da semana#27](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/27)
- [x] [Implementar rota para buscar Quest da proxima semana#28](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/28)
- [x] [Implementar rota para buscar Quest atrasadas#29](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/29)
### Front-end
- [x] [Criar home quadros#14](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/14)
- [x] [Integrar com a rota de buscar Quests do dia#36](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/36)
- [x] [Integrar com a rota de buscar Quests da semana#37](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/37)
- [x] [Integrar com a rota de buscar Quests da proxima semana#38](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/38)
- [x] [Integrar com a rota de buscar Quests atrasadas#39](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/39)

## Links para acesso do material:
[Link do Figma](https://www.figma.com/file/vFvH2cUu6aDYqFWjMHTIGn/This-is-Me?node-id=7%3A12)
[Link da fonte do titulo](https://fonts.google.com/?query=jura)
[Link das Imagens](https://drive.google.com/drive/folders/19crN-SzJqV69z4VhSZgJugZOhRnHmsgS?usp=sharing)

## Design Tela
![Image](https://user-images.githubusercontent.com/60818421/192308614-39ff5b7e-952f-4ba9-ace8-77d92986fc6d.png)
