### ISSUE TITLE
[US] Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de redefinir a minha senha para acessar a aplicação

### ISSUE THREAD

**Issue by RedfoxGHS** [S204-Inatel-2022-2/This-is-Me-App#29]
## Descrição
Caso o usuário esqueça de sua senha ele poderá requisitar uma nova senha por meio da funcionalidade Recuperação de Senha.
Quando o usuário apertar o botão ESQUECI MINHA SENHA, será redirecionado para tela do envio de e-mail, onde haverá o campo de e-mail e o campo onde deverá colocar o código recebido no e-mail, esse código será enviado para o e-mail correspondente se cadastrado, em seguida se o código confere, será redirecionado para tela de reset password onde há dois campos de senha para verificação da mesma. 

## Historia
Eu como Usuário gostaria que fosse desenvolvida a funcionalidade de redefinir a minha senha para acessar a aplicação

## Fluxo
- Enviar o email com o código
- usuário enviar o código
- Api valida o código
- se sucesso, redireciona o mesmo para tela de redefinição de senha
- se falhar, mantem na mesma tela e mostre uma mensagem de código invalido.

## Regras de negócio:
- Após o usuário apertar ESQUECI A MINHA SENHA ele deverá informar seu e-mail que está cadastrado no sistema.
- Só poderá seguir para tela de RESET PASSWORD se o código de verificação for válido

### Back-end
- [x] [Criar Endpoints de  troca de senha#11](https://github.com/S204-Inatel-2022-2/This-is-Me-API/issues/11)

### Front-end
- [x] [Criar tela de "esqueci minha senha"#40](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/40)
- [x] [Criar tela de reset password#41](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/41)
- [x] [Integrar com rota de "Esqueci minha senha"#42](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/42)
- [x] [Integrar com rota de verificação do código de reset#44](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/44)
- [x] [Integrar com rota de reset password#43](https://github.com/S204-Inatel-2022-2/This-is-Me-App/issues/43)

## Links para acesso do material:
[Link do Figma](https://www.figma.com/file/vFvH2cUu6aDYqFWjMHTIGn/This-is-Me?node-id=7%3A12)
[Link da fonte do titulo](https://fonts.google.com/?query=jura)
[Link das Imagens](https://drive.google.com/drive/folders/19crN-SzJqV69z4VhSZgJugZOhRnHmsgS?usp=sharing)

## Design Tela
![Image](https://user-images.githubusercontent.com/48630726/194675876-79b13606-1f91-46dd-8c0b-dd914e40a30d.png)

**Comment by RedfoxGHS** [comment]
## Bug a ser resolvido na proxima demo

- #60
